### ISSUE TITLE
Add Python Style

### ISSUE THREAD

**Issue by mirdaki** [ufosc/resources#9]

**Comment by AustinSmith29** [comment]
Would it be enough to simply give a link to the PEP 8 Style Guide (https://www.python.org/dev/peps/pep-0008/), or would you like a brief overview in addition to the link?

**Comment by mirdaki** [comment]
I think a brief overview would be good. Just enough for a simple example, kinda like the one we have for [general coding guidelines](https://github.com/ufosc/resources/blob/master/coding-guidelines/general-style.md).

**Comment by AustinSmith29** [comment]
Alright, just submitted a Pull Request.

**Comment by mirdaki** [comment]
Completed with Pull Request #13
